In [14]:
if (!require(AHPWR)){
    install.packages("AHPWR")
    library(AHPWR)
}

In [15]:
criteria = c("Cost", "Capacity", "Delivery","Payment Terms","Risk","Sustainability")
wgt_criteria = c(4,5,3,2,2,1) #assign weights for criteria
m_0=matrix_ahp(criteria, wgt_criteria)
m_0

               Cost      Capacity  Delivery  Payment Terms Risk Sustainability
Cost           1.0000000 0.5000000 2.0000000 3.0           3.0  4
Capacity       2.0000000 1.0000000 3.0000000 4.0           4.0  5
Delivery       0.5000000 0.3333333 1.0000000 2.0           2.0  3
Payment Terms  0.3333333 0.2500000 0.5000000 1.0           1.0  2
Risk           0.3333333 0.2500000 0.5000000 1.0           1.0  2
Sustainability 0.2500000 0.2000000 0.3333333 0.5           0.5  1

In [16]:
cost = c("Unit Cost", "Shipping Cost")
wgt_cost = c(3,1)
m_01=matrix_ahp(cost, wgt_cost)
print('Cost Sub-Criteria: m_01')
round(m_01,3)

[1] "Cost Sub-Criteria: m_01"

              Unit Cost Shipping Cost
Unit Cost     1.000     3
Shipping Cost 0.333     1

In [17]:
capacity = c("Production", "MOQ")
wgt_capacity = c(4,1)
m_02=matrix_ahp(capacity, wgt_capacity)
print('Capacity Sub-Criteria: m_02')
round(m_02,3)

[1] "Capacity Sub-Criteria: m_02"

           Production MOQ
Production 1.00       4
MOQ        0.25       1

In [18]:
delivery = c("Lead time", "Logistic Support")
wgt_delivery = c(3,1)
m_03=matrix_ahp(delivery, wgt_delivery)
print('Delivery Sub-Criteria: m_03')
round(m_03,3)

[1] "Delivery Sub-Criteria: m_03"

                 Lead time Logistic Support
Lead time        1.000     3
Logistic Support 0.333     1

In [19]:
risk = c("Reliable", "Currrency Stability")
wgt_risk = c(3,1)
m_05=matrix_ahp(risk, wgt_risk)
print('Risk Sub-Criteria: m_05')
round(m_05,3)

[1] "Risk Sub-Criteria: m_05"

                    Reliable Currrency Stability
Reliable            1.000    3
Currrency Stability 0.333    1

In [20]:
sustainability = c("Social", "Environment")
wgt_sustainability = c(2,1)
m_06=matrix_ahp(sustainability, wgt_sustainability)
print('Sustainability Sub-Criteria: m_06')
round(m_06,3)

[1] "Sustainability Sub-Criteria: m_06"

            Social Environment
Social      1.0    2
Environment 0.5    1

In [21]:
suppliers = c("Southern Monograms", "Hatworx", "Posh Garments", "Repulo Tailors")

# --- 1. Cost ---
# 1.1 Unit Cost
wgt_unitcost = c(6, 3, 7, 10)
m_11 = matrix_ahp(suppliers, wgt_unitcost)

# 1.2 Shipping Cost
wgt_shippingcost = c(7, 9, 4, 2)
m_12 = matrix_ahp(suppliers, wgt_shippingcost)

# --- 2. Capacity ---
# 2.1 Production Capacity
wgt_production = c(4, 2, 10, 8)
m_21 = matrix_ahp(suppliers, wgt_production)

# 2.2 Minimum Order Quantity (MOQ)
wgt_moq = c(10, 6, 5, 10)
m_22 = matrix_ahp(suppliers, wgt_moq)

# --- 3. Delivery ---
# 3.1 Lead Time
wgt_leadtime = c(7, 10, 3, 3)
m_31 = matrix_ahp(suppliers, wgt_leadtime)

# 3.2 Logistics Support
wgt_logisticsupport = c(8, 4, 7, 2)
m_32 = matrix_ahp(suppliers, wgt_logisticsupport)

# --- 4. Payment Terms ---
wgt_paymentterms = c(10, 2, 6, 5)
m_4 = matrix_ahp(suppliers, wgt_paymentterms)

# --- 5. Risk ---
# 5.1 Supply Chain Reliability
wgt_reliable = c(10, 8, 4, 2)
m_51 = matrix_ahp(suppliers, wgt_reliable)

# 5.2 Currency Exchange Rate Stability
wgt_currencyrate = c(10, 10, 5, 4)
m_52 = matrix_ahp(suppliers, wgt_currencyrate)

# --- 6. Sustainability ---
# 6.1 Social Responsibility
wgt_social = c(5, 5, 7, 10)
m_61 = matrix_ahp(suppliers, wgt_social)

# 6.2 Environmental Responsibility
wgt_environment = c(4, 3, 5, 7)
m_62 = matrix_ahp(suppliers, wgt_environment)

# --- Print All Matrices ---
print('1.1 Cost - Unit Cost:')
print(round(m_11, 3))

print('1.2 Cost - Shipping Cost:')
print(round(m_12, 3))

print('2.1 Capacity - Production Capacity:')
print(round(m_21, 3))

print('2.2 Capacity - MOQ:')
print(round(m_22, 3))

print('3.1 Delivery - Lead Time:')
print(round(m_31, 3))

print('3.2 Delivery - Logistics Support:')
print(round(m_32, 3))

print('4. Payment Terms:')
print(round(m_4, 3))

print('5.1 Risk - Reliability:')
print(round(m_51, 3))

print('5.2 Risk - Currency Rate:')
print(round(m_52, 3))

print('6.1 Sustainability - Social:')
print(round(m_61, 3))

print('6.2 Sustainability - Environment:')
print(round(m_62, 3))

[1] "1.1 Cost - Unit Cost:"
                   Southern Monograms Hatworx Posh Garments Repulo Tailors
Southern Monograms               1.00       4           0.5          0.200
Hatworx                          0.25       1           0.2          0.125
Posh Garments                    2.00       5           1.0          0.250
Repulo Tailors                   5.00       8           4.0          1.000
[1] "1.2 Cost - Shipping Cost:"
                   Southern Monograms Hatworx Posh Garments Repulo Tailors
Southern Monograms              1.000   0.333         4.000              6
Hatworx                         3.000   1.000         6.000              8
Posh Garments                   0.250   0.167         1.000              3
Repulo Tailors                  0.167   0.125         0.333              1
[1] "2.1 Capacity - Production Capacity:"
                   Southern Monograms Hatworx Posh Garments Repulo Tailors
Southern Monograms              1.000       3         0.143          0.200
Hatworx                         0.333       1         0.111          0.143
Posh Garments                   7.000       9         1.000          3.000
Repulo Tailors                  5.000       7         0.333          1.000
[1] "2.2 Capacity - MOQ:"
                   Southern Monograms Hatworx Posh Garments Repulo Tailors
Southern Monograms              1.000     5.0             6          1.000
Hatworx                         0.200     1.0             2          0.200
Posh Garments                   0.167     0.5             1          0.167
Repulo Tailors                  1.000     5.0             6          1.000
[1] "3.1 Delivery - Lead Time:"
                   Southern Monograms Hatworx Posh Garments Repulo Tailors
Southern Monograms                1.0   0.250             5              5
Hatworx                           4.0   1.000             8              8
Posh Garments                     0.2   0.125             1              1
Repulo Tailors                    0.2   0.125             1              1
[1] "3.2 Delivery - Logistics Support:"
                   Southern Monograms Hatworx Posh Garments Repulo Tailors
Southern Monograms              1.000   5.000         2.000              7
Hatworx                         0.200   1.000         0.250              3
Posh Garments                   0.500   4.000         1.000              6
Repulo Tailors                  0.143   0.333         0.167              1
[1] "4. Payment Terms:"
                   Southern Monograms Hatworx Posh Garments Repulo Tailors
Southern Monograms              1.000       9           5.0           6.00
Hatworx                         0.111       1           0.2           0.25
Posh Garments                   0.200       5           1.0           2.00
Repulo Tailors                  0.167       4           0.5           1.00
[1] "5.1 Risk - Reliability:"
                   Southern Monograms Hatworx Posh Garments Repulo Tailors
Southern Monograms              1.000   3.000         7.000              9
Hatworx                         0.333   1.000         5.000              7
Posh Garments                   0.143   0.200         1.000              3
Repulo Tailors                  0.111   0.143         0.333              1
[1] "5.2 Risk - Currency Rate:"
                   Southern Monograms Hatworx Posh Garments Repulo Tailors
Southern Monograms              1.000   1.000           6.0              7
Hatworx                         1.000   1.000           6.0              7
Posh Garments                   0.167   0.167           1.0              2
Repulo Tailors                  0.143   0.143           0.5              1
[1] "6.1 Sustainability - Social:"
                   Southern Monograms Hatworx Posh Garments Repulo Tailors
Southern Monograms                  1       1         0.333          0.167
Hatworx                             1       1         0.333          0.167
Posh Garments                       3       3         1.000          0.250
Repulo Tailors                      6       6         4.000          1.000
[1] "6.2 Sustainability - Environment:"
                   Southern Monograms Hatworx Posh Garments Repulo Tailors
Southern Monograms                1.0       2         0.500          0.250
Hatworx                           0.5       1         0.333          0.200
Posh Garments                     2.0       3         1.000          0.333
Repulo Tailors                    4.0       5         3.000          1.000

In [22]:
# map defines the number of subcriteria per criterion - we use it only for the first one (cost)
map <- c(2,2,2,0,2,2) #number of subcriteria for each criteria
# m_0 & m_01 are for criteria & sub-criteria
# m_11, m_12 & m_13 are for alternatives assessed on the first set of subcriteria
# m_2 & m_3 are for alternatives assessed on other criteria
m_ahp<- ahp_s(list(m_0,m_01, m_11, m_12,m_02, m_21, m_22,m_03, m_31, m_32,m_4,m_05, m_51, m_52,m_06, m_61, m_62), map)
m_ahp

   criteria       Weithts    A1          A2          A3          A4
1  Alternatives-> 1.00000000 0.256162953 0.176135434 0.279872799 0.287828814
2  --SC11         0.75000000 0.100546586 0.036260026 0.158278383 0.454915006
3  --SC12         0.25000000 0.069500810 0.143867846 0.024617101 0.012014242
4  -C1            0.24307529 0.041334320 0.043784635 0.044457373 0.113498963
5  --SC21         0.80000000 0.067916838 0.033988178 0.466471026 0.231623957
6  --SC22         0.20000000 0.084139106 0.019293305 0.012428483 0.084139106
7  -C2            0.37674388 0.057286146 0.020073473 0.180422458 0.118961801
8  --SC31         0.75000000 0.185112246 0.473546374 0.045670690 0.045670690
9  --SC32         0.25000000 0.127294064 0.027632293 0.081833308 0.013240335
10 -C3            0.15010520 0.046893811 0.075229523 0.019139013 0.008842851
11 -C4            0.08801040 0.057137323 0.003886094 0.016446050 0.010540930
12 --SC51         0.75000000 0.437316587 0.217147460 0.063672036 0.031863917
13 --SC52         0.25000000 0.107830513 0.107830513 0.020772518 0.013566456
14 -C5            0.08801040 0.047978613 0.028601441 0.007431999 0.003998345
15 --SC61         0.66666667 0.056445978 0.056445978 0.144116706 0.409658005
16 --SC62         0.33333333 0.045908204 0.027917764 0.077434356 0.182073010
17 -C6            0.05405484 0.005532739 0.004560268 0.011975907 0.031985924
   CR
1  0.01160374
2  0.04981122
3  0.05332939
4  0.00000000
5  0.06095434
6  0.01214571
7  0.00000000
8  0.03952908
9  0.03674266
10 0.00000000
11 0.05858989
12 0.06095434
13 0.01353038
14 0.00000000
15 0.02246186
16 0.01892946
17 0.00000000

In [23]:
transforma_tabela(m_ahp)

   criteria       Weithts A1     A2     A3     A4     CR
1  Alternatives-> 100%    25.62% 17.61% 27.99% 28.78% 1.16%
2  --SC11         75%     10.05% 3.63%  15.83% 45.49% 4.98%
3  --SC12         25%     6.95%  14.39% 2.46%  1.2%   5.33%
4  -C1            24.31%  4.13%  4.38%  4.45%  11.35% 0%
5  --SC21         80%     6.79%  3.4%   46.65% 23.16% 6.1%
6  --SC22         20%     8.41%  1.93%  1.24%  8.41%  1.21%
7  -C2            37.67%  5.73%  2.01%  18.04% 11.9%  0%
8  --SC31         75%     18.51% 47.35% 4.57%  4.57%  3.95%
9  --SC32         25%     12.73% 2.76%  8.18%  1.32%  3.67%
10 -C3            15.01%  4.69%  7.52%  1.91%  0.88%  0%
11 -C4            8.8%    5.71%  0.39%  1.64%  1.05%  5.86%
12 --SC51         75%     43.73% 21.71% 6.37%  3.19%  6.1%
13 --SC52         25%     10.78% 10.78% 2.08%  1.36%  1.35%
14 -C5            8.8%    4.8%   2.86%  0.74%  0.4%   0%
15 --SC61         66.67%  5.64%  5.64%  14.41% 40.97% 2.25%
16 --SC62         33.33%  4.59%  2.79%  7.74%  18.21% 1.89%
17 -C6            5.41%   0.55%  0.46%  1.2%   3.2%   0%

In [24]:
rank <- ranque(m_ahp)

In [25]:

# Label criteria and subcriteria
rank$Alternativas <- c("Repulo Tailors","Posh Garments","Southern Monograms", "Hatworx")

# Print final decision matrix with all scores
print("Final AHP Suppliers Ranking:")
rank

[1] "Final AHP Suppliers Ranking:"

  Ranque Alternativas       Pesos
1 1      Repulo Tailors     0.2878288
2 2      Posh Garments      0.2798728
3 3      Southern Monograms 0.2561630
4 4      Hatworx            0.1761354